/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BmButton {
        "size": string;
        "variant": string;
    }
    interface BmHeader {
        "headerAriaAttributes": {};
        /**
          * The `level` property allows users to indicate what header hierarchy this element is. It must take a number from `1` to `6`.
         */
        "level": number;
        /**
          * Provides support for implementing horizontal alignment to the text contained in the header.
         */
        "textAlign": 'left' | 'right' | 'center';
    }
    interface BmRadioButtonGroup {
        "name": any;
    }
    interface BmRadioButtonItem {
        "value": any;
    }
    interface BmStack {
        "gap": 'large' | 'small' | 'none';
        "orientation": Orientation;
    }
    interface HsTextInput {
        "fontStyle": 'normal' | 'italic' | 'oblique' | 'inherit';
    }
}
export interface BmButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBmButtonElement;
}
declare global {
    interface HTMLBmButtonElement extends Components.BmButton, HTMLStencilElement {
    }
    var HTMLBmButtonElement: {
        prototype: HTMLBmButtonElement;
        new (): HTMLBmButtonElement;
    };
    interface HTMLBmHeaderElement extends Components.BmHeader, HTMLStencilElement {
    }
    var HTMLBmHeaderElement: {
        prototype: HTMLBmHeaderElement;
        new (): HTMLBmHeaderElement;
    };
    interface HTMLBmRadioButtonGroupElement extends Components.BmRadioButtonGroup, HTMLStencilElement {
    }
    var HTMLBmRadioButtonGroupElement: {
        prototype: HTMLBmRadioButtonGroupElement;
        new (): HTMLBmRadioButtonGroupElement;
    };
    interface HTMLBmRadioButtonItemElement extends Components.BmRadioButtonItem, HTMLStencilElement {
    }
    var HTMLBmRadioButtonItemElement: {
        prototype: HTMLBmRadioButtonItemElement;
        new (): HTMLBmRadioButtonItemElement;
    };
    interface HTMLBmStackElement extends Components.BmStack, HTMLStencilElement {
    }
    var HTMLBmStackElement: {
        prototype: HTMLBmStackElement;
        new (): HTMLBmStackElement;
    };
    interface HTMLHsTextInputElement extends Components.HsTextInput, HTMLStencilElement {
    }
    var HTMLHsTextInputElement: {
        prototype: HTMLHsTextInputElement;
        new (): HTMLHsTextInputElement;
    };
    interface HTMLElementTagNameMap {
        "bm-button": HTMLBmButtonElement;
        "bm-header": HTMLBmHeaderElement;
        "bm-radio-button-group": HTMLBmRadioButtonGroupElement;
        "bm-radio-button-item": HTMLBmRadioButtonItemElement;
        "bm-stack": HTMLBmStackElement;
        "hs-text-input": HTMLHsTextInputElement;
    }
}
declare namespace LocalJSX {
    interface BmButton {
        "onClicked"?: (event: BmButtonCustomEvent<any>) => void;
        "size"?: string;
        "variant"?: string;
    }
    interface BmHeader {
        "headerAriaAttributes"?: {};
        /**
          * The `level` property allows users to indicate what header hierarchy this element is. It must take a number from `1` to `6`.
         */
        "level"?: number;
        /**
          * Provides support for implementing horizontal alignment to the text contained in the header.
         */
        "textAlign"?: 'left' | 'right' | 'center';
    }
    interface BmRadioButtonGroup {
        "name"?: any;
    }
    interface BmRadioButtonItem {
        "value"?: any;
    }
    interface BmStack {
        "gap"?: 'large' | 'small' | 'none';
        "orientation"?: Orientation;
    }
    interface HsTextInput {
        "fontStyle"?: 'normal' | 'italic' | 'oblique' | 'inherit';
    }
    interface IntrinsicElements {
        "bm-button": BmButton;
        "bm-header": BmHeader;
        "bm-radio-button-group": BmRadioButtonGroup;
        "bm-radio-button-item": BmRadioButtonItem;
        "bm-stack": BmStack;
        "hs-text-input": HsTextInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bm-button": LocalJSX.BmButton & JSXBase.HTMLAttributes<HTMLBmButtonElement>;
            "bm-header": LocalJSX.BmHeader & JSXBase.HTMLAttributes<HTMLBmHeaderElement>;
            "bm-radio-button-group": LocalJSX.BmRadioButtonGroup & JSXBase.HTMLAttributes<HTMLBmRadioButtonGroupElement>;
            "bm-radio-button-item": LocalJSX.BmRadioButtonItem & JSXBase.HTMLAttributes<HTMLBmRadioButtonItemElement>;
            "bm-stack": LocalJSX.BmStack & JSXBase.HTMLAttributes<HTMLBmStackElement>;
            "hs-text-input": LocalJSX.HsTextInput & JSXBase.HTMLAttributes<HTMLHsTextInputElement>;
        }
    }
}
